# -*- coding: utf-8 -*-
"""colab rampex3/5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7dtpCl70JQqv0KhLsXVcNvexU012QyD
"""

s="hello"
s="sdf"+s
print(s)

class Solution:
    def twoSum(self, nums, target):
        a = {}
        for i, num in enumerate(nums):
            result = target - num
            if result in a:
                return [a[result], i]
            a[num] = i

class Solution:
    def middleNode(self,head):
        count =0
        temp =head
        while temp:
            count +=1
            temp =temp.next
        mid =count//2
        temp = head
        for i in range(mid):
            temp = temp.next
        return temp

a = input()
b = input()
ab = sorted(a.replace(' ', '').lower())
ba= sorted(b.replace(' ', '').lower())
if ab == ba:
  print("T")
else:
  print("F")

class Solution:
    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:
        prev = None
        curr = head
        while curr:
            next1=curr.next
            curr.next = prev
            prev = curr
            curr = next1
        return prev

class Solution:
    def isAnagram(self, s: str, t: str) -> bool:
        return sorted(s) == sorted(t)

a = input()
b = input()
ab = sorted(a.replace(' ', '').lower())
ba= sorted(b.replace(' ', '').lower())
if ab == ba:
  print("T")
else:
  print("F")

class Solution:
    def isPalindrome(self, s: str) -> bool:
        s= "".join(filter(str.isalnum, s)).lower()
        if s == s[::-1]:
            return True
        else:
            return False

for i in range(1,6):
    print(i," - ", i*i)

class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        anagram_map = collections.defaultdict(list)

        for s in strs:
            s1 = "".join(sorted(s))
            anagram_map[s1].append(s)
        return list(anagram_map.values())

class Solution:
    def hasCycle(self, head: Optional[ListNode]) -> bool:
        slow = head
        fast = head
        while fast and fast.next:
            slow = slow.next
            fast = fast.next.next
            if slow == fast:
                return True
        return False

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

class Solution:
    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:
        dummy = ListNode()
        current = dummy
        while list1 and list2:
            if list1.val < list2.val:
                current.next = list1
                list1 = list1.next
            else:
                current.next = list2
                list2 = list2.next
            current = current.next
        if list1:
            current.next = list1
        elif list2:
            current.next = list2

        return dummy.next

class Solution:
    def getIntersectionNode(self, headA: ListNode, headB: ListNode) -> Optional[ListNode]:
        a,b, = headA,headB
        while a is not b:
            a= a.next if a else headB
            b= b.next if b else headA
        return a

class Solution:
    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:
        dummy = ListNode(0)
        dummy.next = head
        fast = dummy
        slow = dummy
        for _ in range(n + 1):
            fast = fast.next
        while fast:
            fast = fast.next
            slow = slow.next
        slow.next = slow.next.next
        return dummy.next

from collections import deque
class Solution(object):
    def maxSlidingWindow(self, nums, k):
        n=len(nums)
        dq=deque()
        ans=[]
        for i in range(n):
            while (dq and dq[0]<=i-k):
                dq.popleft()
            while (dq and nums[i]>nums[dq[-1]]):
                dq.pop()
            dq.append(i)
            if (i>=k-1):
                ans.append(nums[dq[0]])
        return ans

class Solution(object):
    def nextGreaterElement(self, nums1, nums2):
        stack=[]
        d={}
        d[nums2[-1]]=-1
        stack.append(nums2[-1])
        for i in range(len(nums2)-2,-1,-1):
            if nums2[i]<stack[-1]:
                d[nums2[i]]=stack[-1]
                stack.append(nums2[i])
                continue
            while (stack and nums2[i]>stack[-1]):
                stack.pop()
            if not stack:
                d[nums2[i]]=-1
                stack.append(nums2[i])
            else:
                d[nums2[i]]=stack[-1]
                stack.append(nums2[i])
        for i in range(len(nums1)):
            nums1[i]=d[nums1[i]]
        return nums1

class Solution(object):
    def dailyTemperatures(self, temperatures):
        n=len(temperatures)
        ans=[0]*n
        stack=[]
        for i in range(n-1,-1,-1):
            while (stack and temperatures[i]>=temperatures[stack[-1]]):
                stack.pop()
            if stack:
                ans[i]=stack[-1]-i
            stack.append(i)
        return ans