# -*- coding: utf-8 -*-
"""colab_rampex3_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/122WtzguvFTpfA1No22YgUQMLCjuQ4oCh
"""

class Solution(object):
    def solveSudoku(self, board):
        rows = [set() for _ in range(9)]
        cols = [set() for _ in range(9)]
        boxes = [set() for _ in range(9)]
        for i in range(9):
            for j in range(9):
                if board[i][j] != '.':
                    num = board[i][j]
                    rows[i].add(num)
                    cols[j].add(num)
                    boxes[(i//3)*3 + j//3].add(num)
        def solve():
            for i in range(9):
                for j in range(9):
                    if board[i][j] == '.':
                        for c in "123456789":
                            box = (i//3)*3 + j//3
                            if c not in rows[i] and c not in cols[j] and c not in boxes[box]:
                                board[i][j] = c
                                rows[i].add(c)
                                cols[j].add(c)
                                boxes[box].add(c)
                                if solve():
                                    return True
                                board[i][j] = '.'
                                rows[i].remove(c)
                                cols[j].remove(c)
                                boxes[box].remove(c)
                        return False
            return True
        solve()

# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right

class Solution:
    def inorderTraversal(self, root: Optional[TreeNode]) -> List[int]:
        result = []
        self.inorder(root, result)
        return result

    def inorder(self, root, result):
        if root is None:
            return

        self.inorder(root.left, result)
        result.append(root.val)
        self.inorder(root.right, result)

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right

class Solution:
    def preorderTraversal(self, root: Optional[TreeNode]) -> List[int]:
        result = []
        self.preorder(root, result)
        return result

    def preorder(self, root, result):
        if root is None:
            return

        result.append(root.val)
        self.preorder(root.left, result)
        self.preorder(root.right, result)

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right

class Solution:
    def postorderTraversal(self, root: Optional[TreeNode]) -> List[int]:
        result = []
        self.postorder(root, result)
        return result

    def postorder(self, root, result):
        if root is None:
            return

        self.postorder(root.left, result)
        self.postorder(root.right, result)
        result.append(root.val)