# -*- coding: utf-8 -*-
"""cola b_rampex3_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pj9j-dn1ReHSN4BnmuN6WeJwpzokeuER
"""

class Solution:
    def fib(self, n: int) -> int:
        if n <= 1:
            return n
        a, b = 0, 1
        for i in range(2, n + 1):
            a, b = b, a + b
        return b

class Solution:
    def isPowerOfTwo(self, n: int) -> bool:
        if (n<=0):
            return False
        while(n%2==0):
            n//=2
        return n==1

class Solution:
    def permute(self, nums: List[int]) -> List[List[int]]:
        result=[]
        self.backtrack(nums,result,[])
        return result
    def backtrack(self,nums,result,temp):
        if (len(nums)==len(temp)):
            result.append(list(temp))
        for num in nums:
            if num in temp:
                continue
            temp.append(num)
            self.backtrack(nums,result,temp)
            temp.pop()

class Solution:
    def subsets(self, nums: List[int]) -> List[List[int]]:
        result = []
        self.backtrack(nums, 0, [], result)
        return result
    def backtrack(self, nums, start, temp, result):
        result.append(list(temp))
        for i in range(start, len(nums)):
            temp.append(nums[i])
            self.backtrack(nums, i + 1, temp, result)
            temp.pop()