# -*- coding: utf-8 -*-
"""colab_rampex3/6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKfZ7dyvfEpVvfweB9sRpVyzrj2-J2IP
"""

class Solution(object):
    def maxVowels(self, s, k):
        vowel={'a','e','i','o','u'}
        count=0
        maxi=0
        for i in range(k):
            if s[i] in vowel:
                count+=1

        maxi=count

        for i in range(k,len(s)):
            if s[i] in vowel:
                count+=1
            if s[i-k] in vowel:
                count-=1

            maxi=max(count,maxi)

        return maxi

class Solution(object):
    def lengthOfLongestSubstring(self, s):
        freq=[-1]*256
        l=0
        r=0
        maxi=0
        while r<len(s):
            if l<=freq[ord(s[r])]:
                l=freq[ord(s[r])]+1
            length=r-l+1
            maxi=max(length,maxi)
            freq[ord(s[r])]=r
            r+=1
        return maxi

class Solution:
    def searchInsert(self, nums: List[int], target: int) -> int:
        left, right = 0, len(nums) - 1
        while left <= right:
            mid = (left + right) // 2
            if nums[mid] == target:
                return mid
            elif nums[mid] < target:
                left = mid + 1
            else:
                right = mid - 1
        return left

class Solution(object):
    def search(self, nums, target):
        a=0
        b=len(nums)-1

        while a<=b:
            m=(a+b)//2

            if nums[m]==target:
                return m
            elif nums[m]<target:
                a=m+1
            else:
                b=m-1

        return -1

class Solution(object):
    def search(self, nums, target):
        l=0
        h=len(nums)-1
        while l<=h:
            mid=(l+h)//2
            if nums[mid]==target:
                return mid
            if nums[l]<=nums[mid]:
                if target>=nums[l] and target<nums[mid]:
                    h=mid-1
                else:
                    l=mid+1

            else:
                if target<=nums[h] and target>nums[mid]:
                    l=mid+1
                else:
                    h=mid-1

        return -1