# -*- coding: utf-8 -*-
"""rampex3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7dtpCl70JQqv0KhLsXVcNvexU012QyD
"""

s="hello"
s="sdf"+s
print(s)

class Solution:
    def twoSum(self, nums, target):
        a = {}
        for i, num in enumerate(nums):
            result = target - num
            if result in a:
                return [a[result], i]
            a[num] = i

class Solution:
    def middleNode(self,head):
        count =0
        temp =head
        while temp:
            count +=1
            temp =temp.next
        mid =count//2
        temp = head
        for i in range(mid):
            temp = temp.next
        return temp

a = input()
b = input()
ab = sorted(a.replace(' ', '').lower())
ba= sorted(b.replace(' ', '').lower())
if ab == ba:
  print("T")
else:
  print("F")

class Solution:
    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:
        prev = None
        curr = head
        while curr:
            next1=curr.next
            curr.next = prev
            prev = curr
            curr = next1
        return prev

class Solution:
    def isAnagram(self, s: str, t: str) -> bool:
        return sorted(s) == sorted(t)

a = input()
b = input()
ab = sorted(a.replace(' ', '').lower())
ba= sorted(b.replace(' ', '').lower())
if ab == ba:
  print("T")
else:
  print("F")

class Solution:
    def isPalindrome(self, s: str) -> bool:
        s= "".join(filter(str.isalnum, s)).lower()
        if s == s[::-1]:
            return True
        else:
            return False

for i in range(1,6):
    print(i," - ", i*i)

class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        anagram_map = collections.defaultdict(list)

        for s in strs:
            s1 = "".join(sorted(s))
            anagram_map[s1].append(s)
        return list(anagram_map.values())

class Solution:
    def hasCycle(self, head: Optional[ListNode]) -> bool:
        slow = head
        fast = head
        while fast and fast.next:
            slow = slow.next
            fast = fast.next.next
            if slow == fast:
                return True
        return False